### ISSUE TITLE
Make sure the right info is in the right place

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-book#29]
Information regarding the same topic should be in the same location in the book, otherwise it is hard to maintain.

Have a look at the book and try to regroup information where it should be.

**Comment by hug-dev** [comment]
More generally, make sure the doc is consistent and well organised.

**Comment by hug-dev** [comment]
Some comments about the book update that need discussion:

# System Architecture example

The [system architecture](https://parallaxsecond.github.io/parsec-book/parsec_service/system_architecture.html) document declares in its introduction:
> This document sets out a system architecture for a deployment of the security service as part of a complete system where it can be used by client applications. This system architecture is constructed around an example deployment where the applications are running in containers within a shared operating system kernel (without full virtualisation). This is not the only possible deployment pattern, and many of the concepts in this document could be adapted to suit other deployments.

This example deployment is used as the "canonical example" of a Parsec deployment and for example the threat model is done against that. The current state of Parsec is very similar apart from the identity provider part (the application lifecycle, the trust relationships between the different components, etc..) Although we do not currently implement exactly that, those parts could be done in the future. I think it makes sense for the Threat Model to be done against that but I am wondering if we should let that example influence other parts of the project, and I am mostly focused about two parts:
* in the [Operations](page), should we keep the Identity Operations and the Trust ones (`AddClient`, `ProveClient` and `ShareTrustBundle`)? Outside of the example described in the system architecture, readers might expect those operations to be implemented in Parsec and they are currently a place holder. We could add them later, if this example deployment gets implemented.
* in the API Overview, for the [auth type field](https://parallaxsecond.github.io/parsec-book/parsec_client/api_overview.html#authentication-and-sessions), we write that a value of two indicates JWT authentication tokens. Similarly the `AuthType` contains a [`JWT`](https://docs.rs/parsec-interface/0.20.2/parsec_interface/requests/enum.AuthType.html#variant.JWT) variant. Should we keep those in both locations even if not currently used?

# Synchronous operation

In [this](https://parallaxsecond.github.io/parsec-book/parsec_client/wire_protocol.html?highlight=synchro#synchronous-operation) section we say:

> The wire protocol operation is synchronous: the client initiates a connection and transmits a request. It then blocks while the service performs the request and transmits the response on the return stream.

Is this a design requirement? If we wanted it, I think it could be possible for clients calls to be asynchronous. At least I believe that Unix Domain Sockets allow that.

# Operations not yet properly designed/thought of

We started implementing contracts for all PSA Crypto operations that were straightforward to do. Most of them are single-part operations. However, in the [operations](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/index.html) page remains all other PSA Crypto operations. They are:
* PsaCopyKey
* PsaPurgeKey
* all multi-parts operations

I think all of those operations need more thinking in the context of Parsec and are not straightforward conversions between a C API to protobuf. I propose to remove them, for now, from the Operations page and add them later (if and) when we decide to implement their Parsec version.

**Comment by ionut-arm** [comment]
> in the API Overview, for the auth type field, we write that a value of two indicates JWT authentication tokens. Similarly the AuthType contains a JWT variant. Should we keep those in both locations even if not currently used?

Alternatively, we can have something like the API coverage page where we specify what's implemented and what's not. We already do this for API calls (as I've mentioned), for client libraries, providers... 

I agree with the other two points.

**Comment by paulhowardarm** [comment]
Happy to remove specs for operations that are not fully defined yet. The open/closed principle allows us to bring those back with full definitions in the future. We also have to remember that the whole "System Architecture" document is now more than a year old and was highly speculative. I think it is still valid as an agnostic/general definition of Parsec in the context of an identity-managed environment, but we need to take it in that spirit rather than being an ultra-precise spec. In the near future we're probably going to have pages that recommend how to manage multi-tenancy in the context of UID-based or SPIFFE-based patterns. We probably could have an intro paragraph at the top of this page to explain this and put it more into context.

On the question of the synchronous wire protocol, that probably should stand for now. Even if we were to introduce an async pattern based on start/poll primitives, that would still be synchronous in terms of the wire protocol. If it's possible to support async interaction in a way that is more "baked in" to the wire protocol, then I suspect that would need some additional design, and it might not be supported in all possible transports. (The wire protocol needs to take care to remain independent of transport).
